version: '3'

volumes:
  db-volume:
    driver: local
    driver_opts:
      device: /Users/kimjiyoon/42Seoul/dockerdata/mariadb
      type: none
      o: bind
  wp-volume:
    driver: local
    driver_opts:
      device: /Users/kimjiyoon/42Seoul/dockerdata/wordpress
      type: none
      o: bind
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    restart: always
    networks:
      - intra
    volumes:
      - db-volume:/var/lib/mysql
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 8080:80
    restart: always
    networks:
      - intra
    volumes:
      - wp-volume:/var/www/html
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    networks:
      - intra
    volumes:
      - wp-volume:/var/www/html
networks:
  intra:
    driver: bridge
